### PR TITLE
Remove windows binary from repo

### PR DESCRIPTION
**Pull request by J0WI**
This is much simpler than https://github.com/containous/traefik-library-image/pull/14#issuecomment-458648877, but because of https://github.com/moby/moby/issues/34819 it's currently only possible on Windows.

### CODE REVIEW

**Comment by ldez** [comment]
Hello, thanks for your contribution.

Our release system is not compatible with this change.

**Comment by J0WI** [comment]
Can you provide some details about these incompatibilities?

**Comment by ldez** [comment]
After some discussions with the team, we think we can accept your PR.

Thank you :+1:

**Comment by ldez** [comment]
https://github.com/docker-library/official-images/pull/5426#issuecomment-462544147

**Pull request merged**
