### PR TITLE
Alpine Docker Healthcheck

### PR DESCRIPTION
**Pull request by EtienneDufresne**
Addresses https://github.com/containous/traefik/issues/1359

Added a default docker healthcheck in the alpine image using wget as it's available.

wget sends exit 1 if it times out or gets a non 200 response back from the /health endpoint.

Let me know if you want the default values for interval, timeout or retries changed.

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @EtienneDufresne, thanks for your contribution!
I would add healthchecks in the official image.
But I see to issues:

1. it will not work because by default, the provider `web` is not activated.
2. we should also add healthchecks support in the `FROM SCRATCH` image. As `curl` is not in here, we may add a basic healthcheck command in the traefik binary.


WDYT @containous/traefik ?

**Comment by vdemeester** [comment]
Right. If we put a healthcheck in the alpine image, we need to put one in the official image (that doesn't have anything except the binary). I am in favor to add an healthcheck but it has to be a traefik daemon feature (as @emilevauge said, this one depends on the web provider to be enabled).

We should add a `traefik healthcheck` command that can return the health of the traefik process and thus that would work for both the official and the alpine image 👼

**Comment by EtienneDufresne** [comment]
I agree that a native traefik healthcheck that does not use curl or wget and that can be used in the `FROM SCRATCH` image would be ideal.

So I guess you can disregard this PR?

I would be happy to help but I might need some guidance!

**Comment by emilevauge** [comment]
@EtienneDufresne 

>So I guess you can disregard this PR?

It may be simpler yes :)

>I would be happy to help but I might need some guidance!

We can definitely help you on this :) And it will be quite simple.
Come say hi on our Slack channel!

**Pull request closed without merging**
